version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: darkbugs_dev
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      APP_NAME: Darkbugs
      DB_USERNAME: postgres
      LAUNCHY_DRY_RUN: 'true'
      BROWSER: /dev/null
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle update && bundle install && yarn install --check-files && bundle exec rake db:create && foreman start -f Procfile.dev"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle/
    ports:
      - "4000:4000"
      - "35729:35729"
      - "3035:3035"
    depends_on:
      - db
    links:
      - db

volumes:
  postgres:
  bundler_gems:
