version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
  web:
    build: .
    environment:
      APP_NAME: Darkbugs
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_HOST: db
      DOMAIN: lvh.me
      LAUNCHY_DRY_RUN: 'true'
      BROWSER: /dev/null
      DEFAULT_TEST_PASS: 'L9<h/(6j5YYS/($jq'
      BUNDLE_PATH: /box
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle install && yarn install --check-files && bundle exec rake db:prepare && RAILS_ENV=test bundle exec rake db:migrate && foreman start -f Procfile.dev"
    volumes:
      - .:/app
      - bundle_path:/box
    ports:
      - "4000:4000"
      - "35729:35729"
      - "3035:3035"
    depends_on:
      - db
    links:
      - db

volumes:
  postgres:
  bundle_path:
