apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: darkbones/darkbugs:latest
          command: ['/bin/sh', '-c']
          args: ['echo CREATING DATABASE && rails db:prepare && echo DONE CREATING DATABASE']
          env:
            - name: DB_HOST
              value: db
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: secrets-db
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: secrets-db
                  key: password
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: secrets-rails
                  key: master_key
            - name: RAILS_ENV
              value: production
