apiVersion: v1
kind: PersistentVolume
metadata:
  name: rails-app-pv
  labels:
    type: local
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rails-app-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
