apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        service: web
    spec:
      containers:
      - args:
        - bash
        - -c
        - rm -f tmp/pids/server.pid && bundle update && bundle install && yarn install --check-files && RAILS_ENV=production rake assets:precompile && bundle exec rails s -p 3000 -b '0.0.0.0' -e production
        image: darkbones/darkbugs:latest
        imagePullPolicy: "Always"
        name: web
        env:
          - name: APP_NAME
            value: Darkbugs
          - name: DB_HOST
            value: db
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets-db
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets-db
                key: password
          - name: RAILS_MASTER_KEY
            valueFrom:
              secretKeyRef:
                name: secrets-rails
                key: master_key
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /darkbugs
          name: web-claim0
        - mountPath: /usr/local/bundle/
          name: bundler-gems
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: bundler-gems
        persistentVolumeClaim:
          claimName: bundler-gems
status: {}
