apiVersion: v1
kind: Service
metadata:
  annotations:
    cmd: kompose convert
    version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    service: web
  name: web
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    service: web
status:
  loadBalancer: {}
