default: &default
  adapter: postgresql
  encoding: utf8
#  host: postgres
#  username: <%#= ENV['DB_USERNAME'] %>
#  password: <%#= ENV['DB_PASSWORD'] %>
  username: db_user
  password: thisisatest
  pool: 5

development:
  <<: *default
  database: darkbugs_development

test:
  <<: *default
  database: darkbugs_test

production:
  url: <%= ENV['DATABASE_URL'] %>
#  <<: *default
#  database: darkbugs_production
