apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rails-app.fullname" . }}
  labels:
    {{- include "rails-app.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "rails-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "rails-app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rails-app.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
#          livenessProbe:
#            httpGet:
#              path: /
#              port: http
#          readinessProbe:
#            httpGet:
#              path: /
#              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DB_HOST
              value: {{ template "rails-app.db.host" . }}
            - name: APP_NAME
              value: {{ template "rails-app.app-name" . }}
            - name: RELEASE_TAG
              value: {{ template "rails-app.release-tag" . }}
            - name: RELEASE_HASH
              value: {{ default "" .Values.global.release.hash }}
            - name: DOMAIN
              value: {{ .Values.domain }}
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.secretName" . }}
                  key: db-username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.secretName" . }}
                  key: db-password
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ template "rails-app.secretName" . }}
                  key: master-key
          args:
            - bash
            - -c
            - rm -f tmp/pids/server.pid && bundle update && bundle install --without development test && RAILS_ENV=production rake db:prepare && RAILS_ENV=production rake assets:precompile && yarn install --check-files && RAILS_ENV=production bundle exec rails s -p 3000 -b '0.0.0.0'
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
