{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rails-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rails-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.com/health-checks: "true"
    nginx.org/health-status-uri: /nginx-health
spec:
  {{- with .Values.ingress }}
  tls:
  - hosts:
  {{- range .hosts }}
    - {{ .host | quote }}
  {{- end }}
    secretName: {{ $.Values.appName | lower }}-tls
  rules:
  {{- range .hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . | quote }}
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
      {{- end }}
  {{- end }}
  - host: "data.darkbugs.com"
    http:
      paths:
      - path: "/"
        backend:
          serviceName: pgweb-svc
          servicePort: 8081
  {{- end }}
  {{- end }}
