{{- if .Values.ingress.enabled -}}
{{- $fullName := include "rails-app.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "rails-app.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
  {{- range .Values.ingress.hosts }}
    - {{ .host | quote }}
  {{- end }}
    secretName: darkbugs-tls
  rules:
  - host: "darkbugs.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
  - host: "*.darkbugs.com"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
  {{- end }}
