apiVersion: v1
kind: Service
metadata:
  name: {{ template "rails-app.fullname" . }}-load-balancer
  labels:
    app: {{ template "rails-app.name" . }}
    chart: {{ template "rails-app.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
  selector:
    {{- include "rails-app.selectorLabels" . | nindent 4 }}
