apiVersion: v1
kind: Service
metadata:
  name: darkbugs-load-balancer
spec:
  type: LoadBalancer
  selector:
    io.kompose.service: web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      name: http
