apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: web
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: web
    spec:
      containers:
      - args:
        - bash
        - -c
        - rm -f tmp/pids/server.pid && bundle install && yarn install --check-files && bundle exec rake db:create && bundle exec rails s -p 3000 -b '0.0.0.0' -e production
        image: darkbones/darkbugs:latest
        imagePullPolicy: ""
        name: web
        env:
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: secrets
                key: username
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secrets
                key: password
        ports:
        - containerPort: 3000
        resources: {}
        volumeMounts:
        - mountPath: /darkbugs
          name: web-claim0
        - mountPath: /usr/local/bundle/
          name: bundler-gems
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: web-claim0
        persistentVolumeClaim:
          claimName: web-claim0
      - name: bundler-gems
        persistentVolumeClaim:
          claimName: bundler-gems
status: {}
